volumes:
  pg_data:
  rustfs_data:
  kafka_data:

services:
  service:
    container_name: image-processor
    image: cosmtrek/air
    ports:
      - "${SERVER_PORT}:8080"
    volumes:
      - ./:/app/service:Z
    working_dir: /app/service
    environment:
      AIR_WD: /app/service

      SERVER_ADDR: "0.0.0.0:8080"

      POSTGRES_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable"
      POSTGRES_MAX_OPEN_CONNS: "${POSTGRES_MAX_OPEN_CONNS}"
      POSTGRES_MAX_IDLE_CONNS: "${POSTGRES_MAX_IDLE_CONNS}"
      POSTGRES_CONN_MAX_LIFETIME: "${POSTGRES_CONN_MAX_LIFETIME}"

      S3_ENDPOINT: "http://rustfs:9000"
      S3_ACCESS_KEY: "${RUSTFS_ACCESS_KEY}"
      S3_SECRET_KEY: "${RUSTFS_SECRET_KEY}"
      S3_REGION: "us-east-1"
      S3_BUCKET_NAME: "${RUSTFS_BUCKET_NAME}"

      KAFKA_ADDR: "kafka:9093"
      KAFKA_TOPIC: "${KAFKA_TOPIC}"
      KAFKA_PRODUCER_RETRY_ATTEMPTS: "${KAFKA_PRODUCER_RETRY_ATTEMPTS}"
      KAFKA_PRODUCER_RETRY_DELAY: "${KAFKA_PRODUCER_RETRY_DELAY}"
      KAFKA_PRODUCER_RETRY_BACKOFF: "${KAFKA_PRODUCER_RETRY_BACKOFF}"
      KAFKA_PRODUCER_BUFFER_SIZE: "${KAFKA_PRODUCER_BUFFER_SIZE}"
      KAFKA_PRODUCER_NUM_WORKERS: "${KAFKA_PRODUCER_NUM_WORKERS}"
      KAFKA_CONSUMER_RETRY_ATTEMPTS: "${KAFKA_CONSUMER_RETRY_ATTEMPTS}"
      KAFKA_CONSUMER_RETRY_DELAY: "${KAFKA_CONSUMER_RETRY_DELAY}"
      KAFKA_CONSUMER_RETRY_BACKOFF: "${KAFKA_CONSUMER_RETRY_BACKOFF}"
      KAFKA_CONSUMER_GROUP_ID: "${KAFKA_CONSUMER_GROUP_ID}"

      IMAGE_PROCESSING_TIMEOUT: "${IMAGE_PROCESSING_TIMEOUT}"
      IMAGE_PROCESSING_RESIZE_FACTOR: "${IMAGE_PROCESSING_RESIZE_FACTOR}"
      IMAGE_PROCESSING_WATERMARK_PATH: "/app/service/watermark.png"
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      kafka-init:
        condition: service_completed_successfully
      rustfs:
        condition: service_healthy

  postgres:
    container_name: image-processor_postgres
    image: postgres:18
    restart: unless-stopped
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      - pg_data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  rustfs:
    container_name: image-processor_rustfs
    image: rustfs/rustfs:1.0.0-alpha.78
    restart: unless-stopped
    ports:
      - "9010:9000"
      - "9011:9001"
    environment:
      RUSTFS_ACCESS_KEY: "${RUSTFS_ACCESS_KEY}"
      RUSTFS_SECRET_KEY: "${RUSTFS_SECRET_KEY}"
    volumes:
      - rustfs_data:/data
    healthcheck:
      test:
        [
          "CMD",
          "sh", "-c",
          "curl -f http://localhost:9000/health && curl -f http://localhost:9001/rustfs/console/health"
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  kafka:
    container_name: image-processor_kafka
    image: confluentinc/cp-kafka:8.0.3
    restart: unless-stopped
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/var/lib/kafka/data
    environment:
      - KAFKA_NODE_ID=0
      - KAFKA_PROCESS_ROLES=controller,broker
      - KAFKA_CONTROLLER_QUORUM_VOTERS=0@127.0.0.1:9094
      - KAFKA_LISTENERS=PLAINTEXT://:9093,EXTERNAL://:9092,CONTROLLER://:9094
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9093,EXTERNAL://localhost:9092
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - CLUSTER_ID="yurOlwKXTsaSaosPMiBZ-w"
    healthcheck:
      test: [ "CMD-SHELL", "/bin/kafka-topics --bootstrap-server 127.0.0.1:9093 --list" ]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 20s

  kafka-init:
    container_name: image-processor_kafka-init
    image: confluentinc/cp-kafka:8.0.3
    environment:
      KAFKA_TOPIC: ${KAFKA_TOPIC}
    entrypoint:
      - /bin/sh
      - -c
      - |
        kafka-topics --bootstrap-server kafka:9093 \
        --create \
        --if-not-exists \
        --topic $$KAFKA_TOPIC \
        --replication-factor 1 \
        --partitions 1
    depends_on:
      kafka:
        condition: service_healthy

  kafka-ui:
    container_name: image-processor_kafka-ui
    image: provectuslabs/kafka-ui:latest
    restart: unless-stopped
    ports:
      - "8088:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local-image-processor-cluster
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9093
    depends_on:
      - kafka
